package org.smartreaction.starrealms.model;

public enum CardSet
{
    CORE,
    PROMO_YEAR_1,
    CRISIS_BASES_AND_BATTLESHIPS,
    CRISIS_EVENTS,
    CRISIS_FLEETS_AND_FORTRESSES,
    CRISIS_HEROES,
    COLONY_WARS,
    GAMBITS,
    UNITED_ASSAULT,
    UNITED_COMMAND,
    UNITED_HEROES,
    UNITED_MISSIONS,
    SCENARIOS
}
